[en]
title = "Harper Reed's Blog"
label = "English 🇺🇸"
locale = "en-US"
contentDir = "content"
weight = 1

[en.params]
description = "Some writing by Harper Reed. Mostly about technology, politics, and things"
subtitle = "Musing from a normal person doing normal things"

[ja]
title = "ハーパー・リードのブログ"
label = "日本語 🇯🇵"
locale = "ja"
weight = 2

[ja.params]
description = "Harper Reedによるいくつかの文章。主にテクノロジー、政治、その他のことについて"
subtitle = "普通の人が普通のことを考える随想"

[es]
title = "Blog de Harper Reed"
label = "Español 🇪🇸"
locale = "es"
weight = 3

[es.params]
description = "Algunos escritos de Harper Reed. Principalmente sobre tecnología, política y otras cosas"
subtitle = "Reflexiones de una persona normal haciendo cosas normales"


[ko]
title = "하퍼 리드의 블로그"
label = "한국어 🇰🇷"
locale = "ko"
weight = 4

[ko.params]
description = "하퍼 리드가 쓴 글들. 주로 기술, 정치, 그리고 다양한 것들에 대해 씁니다"
subtitle = "평범한 사람이 평범한 일을 하며 남기는 생각들"

[zh]
title = "哈珀·雷德的博客"
label = "中文 🇨🇳"
locale = "zh-CN"
weight = 5

[zh.params]
description = "Harper Reed写的一些文章。主要关于技术、政治和其他事情"
subtitle = "一个普通人做普通事情时的思考"

# [it]
# title = "Harper Reed's Blog"
# label = "Italiano 🇮🇹"
# locale = "it"
# contentDir = "content"
# weight = 7

# [it.params]
# description = "Alcuni scritti di Harper Reed. Principalmente su tecnologia, politica e altre cose"
# subtitle = "Riflessioni di una persona normale che fa cose normali"

# [fr]
# title = "Blog de Harper Reed"
# label = "Français 🇫🇷"
# locale = "fr"
# contentDir = "content"
# weight = 8

# [fr.params]
# description = "Des écrits de Harper Reed. Principalement sur la technologie, la politique et d'autres choses"
# subtitle = "Réflexions d'une personne normale qui fait des choses normales"

# [de]
# title = "Harper Reed's Blog"
# label = "Deutsch 🇩🇪"
# locale = "de"
# contentDir = "content"
# weight = 9

# [de.params]
# description = "Einige Schriften von Harper Reed. Hauptsächlich über Technologie, Politik und andere Dinge"
# subtitle = "Denkungen einer normalen Person, die normaler Dinge macht"

[id]
title = "Harper Reed's Blog"
label = "Indonesia 🇮🇩"
locale = "id"
contentDir = "content"
weight = 10

[id.params]
description = "Beberapa tulisan dari Harper Reed. Utama tentang teknologi, politik, dan hal lainnya"
subtitle = "Pikiran dari seorang orang biasa yang melakukan hal-hal biasa"
