######### menu #########

[[main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[main]]
identifier = "notes"
name = "Notes"
url = "/notes/"
weight = 2

[[main]]
identifier = "books"
name = "Books"
url = "/media/books/"
weight = 3

[[main]]
identifier = "links"
name = "Links"
url = "/media/links/"
weight = 4

[[main]]
identifier = "music"
name = "Music"
url = "/media/music/"
weight = 5

[[footer]]
identifier = "contact"
name = "harper@modest.com"
url = "mailto:harper@modest.com"
weight = 1

[[footer]]
identifier = "personal"
name = "Harper.lol"
url = "https://harper.lol"
weight = 5
