######### menu #########


[[main]]
identifier = "contact"
name = "harper@modest.com"
url = "mailto:harper@modest.com"
weight = 6


[[footer]]
identifier = "personal"
name = "Harper.lol"
url = "https://harper.lol"
weight = 5
