[tasks.clean_llm_outputs]
run = "find . -name 'output.txt' -print -delete"
description = 'Remove all the various output.txts'
hide = true

[tasks.clean_hugo_build_lock_file]
run = "find . -name '.hugo_build.lock' -print -delete"
description = 'Remove public directory'
hide = true

[tasks.clean_node_modules]
run = "rm -rf node_modules"
description = 'Remove all the node_modules'
hide = true

[tasks.clean_public_dir]
run = "rm -rf public"
description = 'Remove public directory'
hide = true

[tasks.clean]
depends = [
  'clean_llm_outputs',
  'clean_public_dir',
  'clean_hugo_build_lock_file',
  'clean_node_modules',
]
description = 'Clean up the project: remove all the output.txts and node_modules'

[tasks.install_deps]
run = "yarn"
description = 'Install deps'

[tasks.build]
depends = ['clean_public_dir']
run = "hugo --gc --minify --templateMetrics --templateMetricsHints --forceSyncStatic"
description = 'Build hugo'

[tasks.complete_build]
depends = ['install_deps', 'update_modules', 'build']
description = 'Build hugo'

[tasks.preview_build]
run = "hugo server --disableFastRender --navigateToChanged --templateMetrics --templateMetricsHints --watch --forceSyncStatic -e production --minify"
description = 'Preview build hugo'


[tasks.update_modules]
run = "hugo mod clean --all && hugo mod get -u ./... && hugo mod tidy"
description = 'Update Modules'

[tasks.build_and_deploy]
depends = ['complete_build']
run = "firebase deploy --only hosting"
description = 'Build and Deploy'

[tasks."llm:generate_bundle"]
description = 'Generate LLM bundle output file using repomix'
hide = true # hide this task from the lis
run = """
#!/usr/bin/env bash
npx repomix --style xml --output-show-line-numbers --output output.txt --ignore **/uv.lock,**/package-lock.json,**/.env,content,assets,resources,static,functions,public,data,**/Cargo.lock,**/node_modules,**/target,**/dist,**/build,**/output.txt,**/yarn.lock
"""

[tasks.get_photos] # hide this task from the list
description = 'Grab photos from google'
# you can specify a multiline script instead of individual commands
run = """
#!/usr/bin/env bash
cd tools
python get_photos.py

"""
