name: Run Spotify Tracks Script

on:
    schedule:
        - cron: "0 */12 * * *" # Runs every 12 hours
    workflow_dispatch: # Allows manual triggering

# Add concurrency control
concurrency:
    group: spotify-tracks-${{ github.ref }}
    cancel-in-progress: true

jobs:
    update-spotify-tracks:
        runs-on: ubuntu-latest
        env:
            SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
            SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
            SPOTIFY_REDIRECT_URI: ${{ secrets.SPOTIFY_REDIRECT_URI }}
            SPOTIFY_TOKEN_CACHE: ${{ secrets.SPOTIFY_TOKEN_CACHE }}
            SPOTIFY_TOKEN_CACHE_PATH: .spotify_cache

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "latest"
                  enable-cache: true

            - name: Run spotify tracks script
              working-directory: ./tools
              run: uv run grab_spotify_tracks.py

            - name: Commit and push if changes
              run: |
                  git config --global user.name 'GitHub Action'
                  git config --global user.email 'action@github.com'
                  git add -A
                  git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update spotify tracks" && git push)
