name: Run Starred Links Script

on:
    schedule:
        - cron: "*/30 * * * *" # Runs every 30 minutes
    workflow_dispatch: # Allows manual triggering

jobs:
    update-starred-links:
        runs-on: ubuntu-latest
        env:
            LINKS_RSS_URL: ${{ secrets.LINKS_RSS_URL }}
            LINKS_HUGO_CONTENT_DIR: ../content/links
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
            FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
            OPENAI_MODEL: "gpt-4o-mini"

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Install the latest version of uv
              uses: astral-sh/setup-uv@v3
              with:
                  version: "latest"
                  enable-cache: true

            - name: Cache Script Cache directory
              uses: actions/cache@v3
              with:
                  path: ./tools/.script_cache
                  key: openai-cache-${{ github.sha }}
                  restore-keys: openai-cache-

            - name: Run links script
              working-directory: ./tools
              run: uv run grab_starred_links.py

            - name: Commit and push if changes
              run: |
                  git config --global user.name 'GitHub Action'
                  git config --global user.email 'action@github.com'
                  git add -A
                  git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update micro posts" && git push)
